-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 18:46:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema batailleNavale
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema batailleNavale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `batailleNavale` DEFAULT CHARACTER SET utf8 ;
USE `batailleNavale` ;

-- -----------------------------------------------------
-- Table `batailleNavale`.`bateau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `batailleNavale`.`bateau` (
  `idbateau` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idbateau`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batailleNavale`.`plateau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `batailleNavale`.`plateau` (
  `idplateau` INT NOT NULL AUTO_INCREMENT,
  `placeX` MEDIUMINT(7) NULL,
  `placeY` MEDIUMINT(7) NULL,
  PRIMARY KEY (`idplateau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batailleNavale`.`position2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `batailleNavale`.`position2` (
  `bateau_idbateau` INT NOT NULL,
  `plateau_idplateau` INT NOT NULL,
  PRIMARY KEY (`bateau_idbateau`, `plateau_idplateau`),
  INDEX `fk_bateau_has_plateau_plateau1_idx` (`plateau_idplateau` ASC) ,
  INDEX `fk_bateau_has_plateau_bateau_idx` (`bateau_idbateau` ASC) ,
  CONSTRAINT `fk_bateau_has_plateau_bateau`
    FOREIGN KEY (`bateau_idbateau`)
    REFERENCES `batailleNavale`.`bateau` (`idbateau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bateau_has_plateau_plateau1`
    FOREIGN KEY (`plateau_idplateau`)
    REFERENCES `batailleNavale`.`plateau` (`idplateau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;